name: build and push docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: neurosnap/ptun:latest
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          USERNAME: erock
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/v2/nvimsh/tags/list"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
          --health-start-period 10s
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        network: host
        push: true
        tags: localhost:5000/nvimsh:latest
        driver-opts: network=host
