name: build and push docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: neurosnap/ptun
        volumes:
          - ${{ github.workspace }}/keys:/keys
        options: --name registry
    steps:
    - name: Connect to registry
      shell: bash
      run: |
        echo -e "${{ secrets.PRIVATE_KEY }}" > ./keys/registry
        chmod 600 key
    - name: Restart registry service container
      uses: docker://docker
      with:
        args: docker restart registry
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: localhost:8443/nvimsh:latest
