name: build and push docker image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: neurosnap/ptun:latest
        env:
          USERNAME: erock
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        ports:
          - 5000:5000
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: network=host
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: localhost:5000/nvimsh:latest
